version: '3.6'

services:
  mainnet:
    image: realnuts/docker_dashd:0.15.0-0
    restart: always
    user: root
    ports:
      - "9998:9998"
    volumes:
      - /opt/dash/keys/mainnet:/dash/wallet
      - /opt/dash/mainnet:/dash/.dashcore/blocks
      - /opt/dash/config/mainnet-dash.conf:/dash/.dashcore/dash.conf

  testnet:
    image: realnuts/docker_dashd:0.15.0-0
    restart: always
    user: root
    ports:
      - "19998:19998"
    volumes:
      - /opt/dash/keys/testnet:/dash/wallet
      - /opt/dash/blocks/testnet:/dash/.dashcore/testnet3/blocks
      - /opt/dash/config/testnet-dash.conf:/dash/.dashcore/dash.conf
