version: '3.6'

services:
  dashcoin:
    restart: always
    image: realnuts/docker_dashd:v1.0.15.0.0
    ports:
      - "9998:9998"
      - "9999:9999"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/dash_data:/dash/data
    command:
       - "-printtoconsole"
       - "-regtest=0"
       - "-rest"
       - "-rpcallowip=0/32"
       - "-rpcallowip=172.17.0.0/16"
       - "-rpcpassword=test"
       - "-wallet=wallet1"
       - "-rpcport=8333"
       - "-rpcuser=foo"
       - "-server"
