version: '3.6'

services:
  dashcoin:
    restart: always
    image: realnuts/docker_dashd:0.15.0.0
    ports:
      - "9998:9998"
      - "9999:9999"
    volumes:
      - /opt/blockchain_data/dash_data:/home/dashcore/.dashcore/
      - ./config/mainnet.conf:/home/dashcore/.dashcore/dash.conf
